[package]
name = "benchmark-typedb"
version.workspace = true
edition.workspace = true

[dependencies]
benchmark-core = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = "0.1"
futures = "0.3"
typedb-driver = { workspace = true }
tracing.workspace = true
